development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: stargaze_development
  pool: 5
  username: root
  password:
  host: localhost
  socket: /tmp/mysql.sock

test: &test
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: stargaze_test 
  pool: 5
  username: root
  password:
  host: localhost

production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
